check that all zoomifications files exist

diff --git a/zooma-mappings-wf/Snakefile b/zooma-mappings-wf/Snakefile
--- a/zooma-mappings-wf/Snakefile
+++ b/zooma-mappings-wf/Snakefile
@@ -304,6 +304,19 @@ rule split_zooma_mapping_report:
         echo {params.zoomaMappingReport}
 
         # generate $zoomaMappingReport.aux from all accessions at once
+	
+	# first check that zoomifications files exists
+	missingzoomi=false
+       	for acc in {params.accs}; do
+       	    if ! [ -f {params.working_directory}/${{acc}}/${{acc}}-zoomifications-log.tsv ]; then
+            	echo "zoomifications-log.tsv not found for ${{acc}}"
+		missingzoomi=true
+       	    fi
+        done	
+	if [ "$missingzoomi" = true ] ; then
+       	    echo 'Exiting execution due to missing zoomification files'
+       	    exit 1
+	fi
 
         for acc in {params.accs}; do
        	    cat {params.working_directory}/${{acc}}/${{acc}}-zoomifications-log.tsv >> {params.zoomaMappingReport}.aux
