add missing quotes

diff --git a/zooma-mappings-wf/Snakefile b/zooma-mappings-wf/Snakefile
--- a/zooma-mappings-wf/Snakefile
+++ b/zooma-mappings-wf/Snakefile
@@ -308,13 +308,13 @@ rule split_zooma_mapping_report:
 	# first check that zoomifications files exists
 	missingzoomi=false
        	for acc in {params.accs}; do
-       	    if ! [ -f {params.working_directory}/${{acc}}/${{acc}}-zoomifications-log.tsv ]; then
+       	    if ! [ -f "{params.working_directory}/${{acc}}/${{acc}}-zoomifications-log.tsv" ]; then
             	echo "zoomifications-log.tsv not found for ${{acc}}"
 		missingzoomi=true
        	    fi
         done	
 	if [ "$missingzoomi" = true ] ; then
-       	    echo 'Exiting execution due to missing zoomification files'
+       	    echo "Exiting execution due to missing zoomification files"
        	    exit 1
 	fi
 
