fix logic in rule run_condense_sdrf

diff --git a/zooma-mappings-wf/Snakefile b/zooma-mappings-wf/Snakefile
--- a/zooma-mappings-wf/Snakefile
+++ b/zooma-mappings-wf/Snakefile
@@ -146,12 +146,12 @@ rule run_condense_sdrf:
         exec &> "{log}"
 
         # For condense_sdrf.pl, get_experiment_type_from_xml.pl
-        #export PATH={params.script_dir}/db/scripts:$PATH
+        # export PATH={params.script_dir}/db/scripts:$PATH
         # source bash functions
-        source {params.script_dir}/bash_util/generic_routines.sh
+        # source {params.script_dir}/bash_util/generic_routines.sh
         echo "attempt: {resources.attempt_number}"
 
-        pushd {params.working_directory}/{wildcards.accession}
+        pushd {params.working_directory} #/{wildcards.accession}
 
         if [ {params.mode} == "atlas" ] || [ {params.mode} == "irap_single_lib" ]; then
                 # Get idf file
@@ -159,7 +159,7 @@ rule run_condense_sdrf:
         fi
 
 
-        if [[ {resources.attempt_number} -lt 2 ]]; then
+        if [[ {resources.attempt_number} -eq 1 ]]; then
             # Run condense_sdrf.pl with options to map terms with Zooma (-z) and import
             # the IDF from ArrayExpress load directory (-i).
             if [ {params.mode} == "atlas" ]; then
@@ -185,37 +185,39 @@ rule run_condense_sdrf:
                 exit 1
             fi
         
-        elif [[ {params.retry_without_zooma} == "yes" ]]; then
-
-            # if error detected, then condense SDRF without Zooma mapping
-
-            if [ {params.mode} == "atlas" ]; then
-
-                expType=$(perl {params.script_dir}/db/scripts/get_experiment_type_from_xml.pl {input})
-                echo $expType
-
-                if [[ $expType == *baseline ]]; then
-                    {params.experiment_metadata_dir}/condense_sdrf.pl -e {wildcards.accession} -f {params.working_directory}/{wildcards.accession}/{wildcards.accession}-factors.xml -i -o {params.working_directory}/{wildcards.accession} -x {params.zooma_exclusions} -fi $idf_path
-                else
-                    {params.experiment_metadata_dir}/condense_sdrf.pl -e {wildcards.accession} -i -o {params.working_directory}/{wildcards.accession} -fi $idf_path
-                fi
-            elif [ {params.mode} == "single_cell" ]; then
-                export EXP_ID={wildcards.accession}
-                export SKIP_ZOOMA="yes" 
-                {params.experiment_metadata_dir}/single_cell_condensed_sdrf.sh
-
-            elif [ {params.mode} == "irap_single_lib" ]; then
-                # also collect biological replicate IDs for irap_single_lib mode
-                {params.experiment_metadata_dir}/condense_sdrf.pl -e {wildcards.accession} -b -i -o {params.working_directory}/{wildcards.accession} -fi $idf_path
-            else
-                echo "Mode {params.mode} not recognised."
-                exit 1
-            fi
         else
-            echo "Failed to condense SDRF for {wildcards.accession}"
+
+            if [[ {params.retry_without_zooma} == "yes" ]]; then
+
+                echo "Error detected, try to condense SDRF without Zooma mapping"
+
+                if [ {params.mode} == "atlas" ]; then
+
+                    expType=$(perl {params.script_dir}/db/scripts/get_experiment_type_from_xml.pl {input})
+                    echo $expType
+
+                    if [[ $expType == *baseline ]]; then
+                        {params.experiment_metadata_dir}/condense_sdrf.pl -e {wildcards.accession} -f {params.working_directory}/{wildcards.accession}/{wildcards.accession}-factors.xml -i -o {params.working_directory}/{wildcards.accession} -x {params.zooma_exclusions} -fi $idf_path
+                    else
+                        {params.experiment_metadata_dir}/condense_sdrf.pl -e {wildcards.accession} -i -o {params.working_directory}/{wildcards.accession} -fi $idf_path
+                    fi
+                elif [ {params.mode} == "single_cell" ]; then
+                    export EXP_ID={wildcards.accession}
+                    export SKIP_ZOOMA="yes" 
+                    {params.experiment_metadata_dir}/single_cell_condensed_sdrf.sh
+
+                elif [ {params.mode} == "irap_single_lib" ]; then
+                    # also collect biological replicate IDs for irap_single_lib mode
+                    {params.experiment_metadata_dir}/condense_sdrf.pl -e {wildcards.accession} -b -i -o {params.working_directory}/{wildcards.accession} -fi $idf_path
+                else
+                    echo "Mode {params.mode} not recognised."
+                    exit 1
+                fi
+
+            fi
         fi
 
-        # check if successful
+        # check if condense SDRF was successful 
         if [ ! -s "{params.working_directory}/{wildcards.accession}/{wildcards.accession}.condensed-sdrf.tsv" ]; then
 	        echo "ERROR: Failed to generate {params.working_directory}/{wildcards.accession}/{wildcards.accession}.condensed-sdrf.tsv"
             rm -rf {params.working_directory}/{wildcards.accession}/{wildcards.accession}-zoomifications-log.tsv
@@ -295,6 +297,7 @@ rule split_zooma_mapping_report:
         """
         set -e # snakemake on the cluster doesn't stop on error when --keep-going is set
         exec &> "{log}"
+        echo {params.zoomaMappingReport}
 
         if [ ! -s "{params.zoomaMappingReport}.aux" ]; then
             echo "ERROR: Something went wrong with condense_sdrf.pl run with Zooma mappings - no report is available" 
