new rule to create .aux

diff --git a/zooma-mappings-wf/Snakefile b/zooma-mappings-wf/Snakefile
--- a/zooma-mappings-wf/Snakefile
+++ b/zooma-mappings-wf/Snakefile
@@ -216,21 +216,31 @@ rule run_condense_sdrf:
 
         # check if condense SDRF was successful 
         if [ ! -s "{params.working_directory}/{wildcards.accession}/{wildcards.accession}.condensed-sdrf.tsv" ]; then
-	        echo "ERROR: Failed to generate {params.working_directory}/{wildcards.accession}/{wildcards.accession}.condensed-sdrf.tsv"
+            echo "ERROR: Failed to generate {params.working_directory}/{wildcards.accession}/{wildcards.accession}.condensed-sdrf.tsv"
             rm -rf {params.working_directory}/{wildcards.accession}/{wildcards.accession}-zoomifications-log.tsv
-	        exit 1
+            exit 1
         else
             echo "All condense_sdrf tasks now done"
             echo "Updated condensed sdrf and idf files for all experiments"
 
-            cat {params.working_directory}/{wildcards.accession}/{wildcards.accession}-zoomifications-log.tsv >> {params.zoomaMappingReport}.aux
-            rm -rf {params.working_directory}/{wildcards.accession}/{wildcards.accession}-zoomifications-log.tsv
             touch {output.done}
         fi
         popd
         """
 
+rule compile_aux_file:
+    log:
+    input:
+        get_split_zooma_mapping_report_inputs(ACCESSIONS, logs_path)
+    shell:
+        """
+        set -e # snakemake on the cluster doesn't stop on error when --keep-going is set
+        exec &> "{log}"
 
+       	cat {params.working_directory}/{wildcards.accession}/{wildcards.accession}-zoomifications-log.tsv >> {params.zoomaMappingReport}.aux
+      	rm -rf {params.working_directory}/{wildcards.accession}/{wildcards.accession}-zoomifications-log.tsv
+        """
+	
 rule apply_fixes:
     """
     Apply automatic fixes to all imported sdrf and idf files
@@ -276,7 +286,7 @@ rule apply_fixes:
         popd
 	
         if [ {params.keep_backup_sdrf} == "false" ]; then
-	        # remove backup of old condensed
+            # remove backup of old condensed
             rm -rf {params.working_directory}/{wildcards.accession}/{wildcards.accession}.condensed-sdrf.tsv.bak
         fi
         """
